# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20190316_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Login_Table',
        ),
    ]
