# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20190321_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=50)),
                ('Book_name', models.CharField(max_length=30)),
                ('book_status', models.BooleanField()),
                ('book_description', models.CharField(max_length=100)),
            ],
        ),
    ]
